import type { Property } from './types';

// Helper function to generate a random offset for coordinates
const randomCoordOffset = () => (Math.random() - 0.5) * 0.1;

export const MOCK_PROPERTIES: Property[] = [
  // Buy Properties
  {
    id: 'buy-1',
    title: 'Palm Grove Villa',
    price: 32000000,
    location: { address: 'Bandra, Mumbai', city: 'Mumbai', lat: 19.0596 + randomCoordOffset(), lng: 72.8406 + randomCoordOffset() },
    type: 'Villa',
    status: 'For Sale',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    description: 'A luxurious 4BHK villa surrounded by palm trees and a private pool.',
    amenities: ['Private Pool', 'Garden', 'Parking', '24/7 Security'],
    images: ['https://picsum.photos/seed/buy1/800/600', 'https://picsum.photos/seed/buy1a/800/600', 'https://picsum.photos/seed/buy1b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: true,
    approved: true,
    createdAt: '2023-11-01T10:00:00Z',
    image_prompt: "modern tropical villa with palm trees, private pool, sunny weather, luxury Indian architecture, realistic lighting"
  },
  {
    id: 'buy-2',
    title: 'Skyline Heights',
    price: 16000000,
    location: { address: 'Powai, Mumbai', city: 'Mumbai', lat: 19.1176 + randomCoordOffset(), lng: 72.9060 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    description: 'Contemporary 3BHK apartment with panoramic city views and glass balconies.',
    amenities: ['City View', 'Balcony', 'Gym', 'Pool'],
    images: ['https://picsum.photos/seed/buy2/800/600', 'https://picsum.photos/seed/buy2a/800/600', 'https://picsum.photos/seed/buy2b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: true,
    approved: true,
    createdAt: '2023-11-02T11:30:00Z',
    image_prompt: "high-rise glass apartment with skyline view, sunset light, modern urban design"
  },
  {
    id: 'buy-3',
    title: 'Silver Maple Residency',
    price: 9500000,
    location: { address: 'Whitefield, Bengaluru', city: 'Bengaluru', lat: 12.9698 + randomCoordOffset(), lng: 77.7500 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    description: 'Spacious 2BHK with smart home features and landscaped gardens.',
    amenities: ['Smart Home', 'Landscaped Garden', 'Clubhouse', 'Security'],
    images: ['https://picsum.photos/seed/buy3/800/600', 'https://picsum.photos/seed/buy3a/800/600', 'https://picsum.photos/seed/buy3b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: true,
    approved: true,
    createdAt: '2023-11-03T09:00:00Z',
    image_prompt: "modern apartment building with green landscaping, smart home interiors, bright daylight"
  },
  {
    id: 'buy-4',
    title: 'The Serenity Estate',
    price: 25000000,
    location: { address: 'Koregaon Park, Pune', city: 'Pune', lat: 18.5362 + randomCoordOffset(), lng: 73.8939 + randomCoordOffset() },
    type: 'House',
    status: 'For Sale',
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    description: 'Luxury bungalow with a minimalist interior and garden-facing balcony.',
    amenities: ['Garden', 'Balcony', 'Minimalist Design', 'Parking'],
    images: ['https://picsum.photos/seed/buy4/800/600', 'https://picsum.photos/seed/buy4a/800/600', 'https://picsum.photos/seed/buy4b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: false,
    approved: true,
    createdAt: '2023-11-04T14:00:00Z',
    image_prompt: "modern Indian bungalow with green garden, minimalist architecture, evening sunlight"
  },
  {
    id: 'buy-5',
    title: 'Lakeview Towers',
    price: 12000000,
    location: { address: 'Thane, Mumbai', city: 'Thane', lat: 19.2183 + randomCoordOffset(), lng: 72.9781 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    description: '3BHK apartment offering serene lake views and a rooftop gym.',
    amenities: ['Lake View', 'Rooftop Gym', 'Pool', 'Security'],
    images: ['https://picsum.photos/seed/buy5/800/600', 'https://picsum.photos/seed/buy5a/800/600', 'https://picsum.photos/seed/buy5b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: false,
    approved: true,
    createdAt: '2023-11-05T16:45:00Z',
    image_prompt: "lake-facing apartment building, calm water reflection, rooftop terrace, blue sky"
  },
  {
    id: 'buy-6',
    title: 'Urban Edge Residences',
    price: 19000000,
    location: { address: 'Gurugram, Haryana', city: 'Gurugram', lat: 28.4595 + randomCoordOffset(), lng: 77.0266 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    description: 'Modern urban apartments with rooftop gardens and coworking spaces.',
    amenities: ['Rooftop Garden', 'Coworking Space', 'Gym', 'City View'],
    images: ['https://picsum.photos/seed/buy6/800/600', 'https://picsum.photos/seed/buy6a/800/600', 'https://picsum.photos/seed/buy6b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: true,
    approved: true,
    createdAt: '2023-11-06T12:00:00Z',
    image_prompt: "modern urban residential building, rooftop garden, coworking lounge, city background"
  },
  {
    id: 'buy-7',
    title: 'Rosewood Park Homes',
    price: 8800000,
    location: { address: 'Hyderabad, Telangana', city: 'Hyderabad', lat: 17.3850 + randomCoordOffset(), lng: 78.4867 + randomCoordOffset() },
    type: 'House',
    status: 'For Sale',
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    description: 'Family-friendly 3BHK with a playground and walking trail.',
    amenities: ['Playground', 'Walking Trail', 'Garden', 'Community Hall'],
    images: ['https://picsum.photos/seed/buy7/800/600', 'https://picsum.photos/seed/buy7a/800/600', 'https://picsum.photos/seed/buy7b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: false,
    approved: true,
    createdAt: '2023-11-07T10:30:00Z',
    image_prompt: "suburban residential homes with green park, walking trail, families, sunny day"
  },
  {
    id: 'buy-8',
    title: 'Oceancrest Apartments',
    price: 14000000,
    location: { address: 'Goa', city: 'Goa', lat: 15.2993 + randomCoordOffset(), lng: 74.1240 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    description: 'Sea-facing 2BHK apartment with a private balcony and beach access.',
    amenities: ['Ocean View', 'Beach Access', 'Balcony', 'Pool'],
    images: ['https://picsum.photos/seed/buy8/800/600', 'https://picsum.photos/seed/buy8a/800/600', 'https://picsum.photos/seed/buy8b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: true,
    approved: true,
    createdAt: '2023-11-08T18:00:00Z',
    image_prompt: "beachfront apartment with ocean view, palm trees, tropical modern design"
  },
  {
    id: 'buy-9',
    title: 'Golden Horizon Enclave',
    price: 11000000,
    location: { address: 'Ahmedabad, Gujarat', city: 'Ahmedabad', lat: 23.0225 + randomCoordOffset(), lng: 72.5714 + randomCoordOffset() },
    type: 'House',
    status: 'For Sale',
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    description: 'Spacious duplex homes with rooftop solar panels and open terraces.',
    amenities: ['Solar Panels', 'Terrace', 'Duplex', 'Garden'],
    images: ['https://picsum.photos/seed/buy9/800/600', 'https://picsum.photos/seed/buy9a/800/600', 'https://picsum.photos/seed/buy9b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: false,
    approved: true,
    createdAt: '2023-11-09T11:00:00Z',
    image_prompt: "eco-friendly duplex homes with solar panels, open terrace, modern Indian style"
  },
  {
    id: 'buy-10',
    title: 'Maplewood Greens',
    price: 13000000,
    location: { address: 'Chandigarh', city: 'Chandigarh', lat: 30.7333 + randomCoordOffset(), lng: 76.7794 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Sale',
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    description: 'Elegant 3BHK apartment complex with a golf-view landscape.',
    amenities: ['Golf View', 'Landscaped Garden', 'Clubhouse', 'Gym'],
    images: ['https://picsum.photos/seed/buy10/800/600', 'https://picsum.photos/seed/buy10a/800/600', 'https://picsum.photos/seed/buy10b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: true,
    approved: true,
    createdAt: '2023-11-10T15:20:00Z',
    image_prompt: "luxury apartment overlooking golf course, greenery, clear sky, premium exterior design"
  },
  // Rent Properties
  {
    id: 'rent-1',
    title: 'Blue Horizon Apartments',
    price: 60000,
    location: { address: 'Versova, Mumbai', city: 'Mumbai', lat: 19.1332 + randomCoordOffset(), lng: 72.8157 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    description: 'Fully furnished 2BHK apartment with sea view and modern interiors.',
    amenities: ['Furnished', 'Sea View', 'Balcony', 'Security'],
    images: ['https://picsum.photos/seed/rent1/800/600', 'https://picsum.photos/seed/rent1a/800/600', 'https://picsum.photos/seed/rent1b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: true,
    approved: true,
    createdAt: '2023-11-11T09:45:00Z',
    image_prompt: "sea-facing apartment with balcony, modern furniture, soft sunlight"
  },
  {
    id: 'rent-2',
    title: 'UrbanNest Studios',
    price: 28000,
    location: { address: 'Koramangala, Bengaluru', city: 'Bengaluru', lat: 12.9352 + randomCoordOffset(), lng: 77.6245 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    description: 'Compact and stylish studio apartments ideal for young professionals.',
    amenities: ['Studio', 'Modern Interior', 'Wi-Fi', 'Parking'],
    images: ['https://picsum.photos/seed/rent2/800/600', 'https://picsum.photos/seed/rent2a/800/600', 'https://picsum.photos/seed/rent2b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: false,
    approved: true,
    createdAt: '2023-11-12T18:00:00Z',
    image_prompt: "compact modern studio apartment, cozy interiors, bright and minimal design"
  },
  {
    id: 'rent-3',
    title: 'Parkside Haven',
    price: 35000,
    location: { address: 'Noida Sector 62, Delhi NCR', city: 'Noida', lat: 28.6196 + randomCoordOffset(), lng: 77.3823 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    description: 'Spacious 3BHK apartment overlooking a lush community park.',
    amenities: ['Park View', 'Spacious', 'Security', 'Playground'],
    images: ['https://picsum.photos/seed/rent3/800/600', 'https://picsum.photos/seed/rent3a/800/600', 'https://picsum.photos/seed/rent3b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: true,
    approved: true,
    createdAt: '2023-11-13T12:15:00Z',
    image_prompt: "modern apartment with green park view, glass windows, families walking outside"
  },
  {
    id: 'rent-4',
    title: 'Cityscape Residences',
    price: 25000,
    location: { address: 'Hinjewadi, Pune', city: 'Pune', lat: 18.5912 + randomCoordOffset(), lng: 73.7389 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 1000,
    description: 'Affordable 2BHK near tech parks with great connectivity and security.',
    amenities: ['Near Tech Park', 'Security', 'Parking', 'Gym'],
    images: ['https://picsum.photos/seed/rent4/800/600', 'https://picsum.photos/seed/rent4a/800/600', 'https://picsum.photos/seed/rent4b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: false,
    approved: true,
    createdAt: '2023-11-14T16:00:00Z',
    image_prompt: "urban apartment near tech park, evening light, gated community"
  },
  {
    id: 'rent-5',
    title: 'Sunrise Apartments',
    price: 32000,
    location: { address: 'Gachibowli, Hyderabad', city: 'Hyderabad', lat: 17.4401 + randomCoordOffset(), lng: 78.3489 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    description: 'Pet-friendly apartment complex with gym and pool access.',
    amenities: ['Pet-Friendly', 'Gym', 'Pool', 'Clubhouse'],
    images: ['https://picsum.photos/seed/rent5/800/600', 'https://picsum.photos/seed/rent5a/800/600', 'https://picsum.photos/seed/rent5b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: false,
    approved: true,
    createdAt: '2023-11-15T10:00:00Z',
    image_prompt: "modern apartment with swimming pool, pet-friendly environment, morning light"
  },
  {
    id: 'rent-6',
    title: 'The Metro Loft',
    price: 45000,
    location: { address: 'Andheri East, Mumbai', city: 'Mumbai', lat: 19.1136 + randomCoordOffset(), lng: 72.8697 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    description: 'Chic loft-style 1BHK with exposed brick interiors and city views.',
    amenities: ['Loft Style', 'Exposed Brick', 'City View', 'Furnished'],
    images: ['https://picsum.photos/seed/rent6/800/600', 'https://picsum.photos/seed/rent6a/800/600', 'https://picsum.photos/seed/rent6b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: true,
    approved: true,
    createdAt: '2023-11-16T13:30:00Z',
    image_prompt: "loft-style apartment, exposed brick wall, city skyline view at night"
  },
  {
    id: 'rent-7',
    title: 'Greenleaf Homes',
    price: 20000,
    location: { address: 'Electronic City, Bengaluru', city: 'Bengaluru', lat: 12.8452 + randomCoordOffset(), lng: 77.6602 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    description: 'Affordable 2BHK surrounded by greenery and calm surroundings.',
    amenities: ['Greenery', 'Peaceful', 'Parking', 'Security'],
    images: ['https://picsum.photos/seed/rent7/800/600', 'https://picsum.photos/seed/rent7a/800/600', 'https://picsum.photos/seed/rent7b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: false,
    approved: true,
    createdAt: '2023-11-17T11:00:00Z',
    image_prompt: "residential building surrounded by trees, peaceful atmosphere, bright daylight"
  },
  {
    id: 'rent-8',
    title: 'Amber Suites',
    price: 30000,
    location: { address: 'Baner, Pune', city: 'Pune', lat: 18.5645 + randomCoordOffset(), lng: 73.7799 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 700,
    description: 'Furnished 1BHK suites with premium interiors and balcony view.',
    amenities: ['Furnished', 'Balcony', 'Premium Interior', 'Gym'],
    images: ['https://picsum.photos/seed/rent8/800/600', 'https://picsum.photos/seed/rent8a/800/600', 'https://picsum.photos/seed/rent8b/800/600'],
    agent: { name: 'Emily White', avatar: 'https://i.pravatar.cc/150?u=emily' },
    featured: false,
    approved: true,
    createdAt: '2023-11-18T14:45:00Z',
    image_prompt: "modern apartment with stylish interior, balcony with city view"
  },
  {
    id: 'rent-9',
    title: 'Cedar Court',
    price: 55000,
    location: { address: 'Gurgaon Sector 54', city: 'Gurugram', lat: 28.4235 + randomCoordOffset(), lng: 77.0945 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    description: 'Luxury 3BHK apartment with clubhouse and community events.',
    amenities: ['Clubhouse', 'Pool', 'Luxury', 'Security'],
    images: ['https://picsum.photos/seed/rent9/800/600', 'https://picsum.photos/seed/rent9a/800/600', 'https://picsum.photos/seed/rent9b/800/600'],
    agent: { name: 'Jane Doe', avatar: 'https://i.pravatar.cc/150?u=jane' },
    featured: true,
    approved: true,
    createdAt: '2023-11-19T10:15:00Z',
    image_prompt: "luxury residential tower, clubhouse area, poolside view, modern exterior"
  },
  {
    id: 'rent-10',
    title: 'Lotus View Apartments',
    price: 38000,
    location: { address: 'Vashi, Navi Mumbai', city: 'Navi Mumbai', lat: 19.0745 + randomCoordOffset(), lng: 72.9978 + randomCoordOffset() },
    type: 'Apartment',
    status: 'For Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 1150,
    description: '2BHK apartment with spacious balcony and skyline view.',
    amenities: ['Balcony', 'Skyline View', 'Parking', 'Gym'],
    images: ['https://picsum.photos/seed/rent10/800/600', 'https://picsum.photos/seed/rent10a/800/600', 'https://picsum.photos/seed/rent10b/800/600'],
    agent: { name: 'John Smith', avatar: 'https://i.pravatar.cc/150?u=john' },
    featured: false,
    approved: true,
    createdAt: '2023-11-20T12:00:00Z',
    image_prompt: "balcony apartment with city skyline, plants, and soft evening light"
  },
];